### ISSUE TITLE
Port to Jekyll

### ISSUE THREAD

**Issue by lunaryorn** [lunaryorn/lunaryorn.github.io#1]
# Tasks

- [x] Add CNAME file
- [x] Add fonts
- [x] Add styles
- [x] Add configuration
- [x] Migrate pages
- [x] Migrate front page
- [x] Migrate posts
- [x] Migrate archive page
- [x] Enable feed plugin
- [x] Enable Twitter cards
- [x] Prepend base url to all URLs
- [x] Convert images to `<figure>` with `<figcaption>`
- [x] Add syntax highlighting stylesheet and check code block styling
- [x] Deploy
- [x] Update colophon and footer
- [x] Add Travis CI configuration to test the site
- [x] Fix htmlproof warnings
- [x] Port remaining makefile targets

As part of this, drop tags, tag pages and tag feeds.  Do consider an Emacs category, though.

**Comment by aminb** [comment]
@lunaryorn May I ask the reasons you migrated from Hakyll to Jekyll?

I know there's the much easier deployment with Jekyll since Github supports it and you basically commit and push, but I'm curious to know if there were other reasons too, since I'm planning to do the opposite, migrate from Jekyll to Hakyll :)

**Comment by lunaryorn** [comment]
@aminb It's easier to deploy and much less work to maintain.

**Comment by aminb** [comment]
@lunaryorn Makes sense, thanks!
